config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'welcome#index'
  resources :bids
  get 'fox_volume', to: 'bids#fox_volume_check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	bids_path
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /bids
  # GET /bids.json
  def index
    response = RestClient.get 'http://api.bitvalor.com/v1/order_book.json'
    data = JSON.parse(response.body)["bids"]
    @fox = data.select {|element| element[0] == "FOX"}
    @b2u = data.select {|element| element[0] == "B2U"}
    @mbt = data.select {|element| element[0] == "MBT"}
  end

  def fox_volume_check
    response = RestClient.get 'http://api.bitvalor.com/v1/order_book.json'
    data = JSON.parse(response.body)["bids"]
    fox = data.select {|element| element[0] == "FOX"}

    greater = fox.select{|array| array[1] > params[:data].to_i }
    @result = greater.sum{|array| array[2]}
    respond_to do |format|
      format.json { render json: @result }
    end

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bids/_form.html.erb
<%= form_with(model: bid, local: true) do |form| %>
  <% if bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
      <% bid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<h1>Listing fetched data from API</h1>
<div class="form-group">
  <label for="bankSelect">Example Bitcoin Banks</label>
  <select class="form-control" id="bankSelect">
    <option>MBT</option>
    <option>B2U</option>
    <option>FOX</option>
  </select>
</div>
<div class="row">
  <label class="col-md-2">Enter Fox Value</label>
  <input type="text" id="fox-amount" class="col-md-2">
  <button id="fox-output" class="col-md-2">Check Volume</button>
  <%= image_tag 'loading.gif', class: 'hide col-md-2 img-circle img-responsive', id: 'loading-img' %>
  <label hidden="true" id="fox-output-label" class="col-md-2">ada</label>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Bitcoin Banks</th>
      <th>Value</th>
      <th>Volume</th>
    </tr>
  </thead>
  <tbody id="mbt-table">
    <%- @mbt.each_with_index do |data, index| %>
      <tr id="mbt">
        <th scope="row"><%= index %></th>
        <td><%= data[0] %></td>
        <td><%= data[1] %></td>
        <td><%= data[2] %></td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="b2u-table">
    <%- @b2u.each_with_index do |data, index| %>
      <tr id="mbt">
        <th scope="row"><%= index %></th>
        <td><%= data[0] %></td>
        <td><%= data[1] %></td>
        <td><%= data[2] %></td>
      </tr>
    <% end %>
  </tbody>
  <tbody id="fox-table">
    <%- @fox.each_with_index do |data, index| %>
      <tr id="mbt">
        <th scope="row"><%= index %></th>
        <td><%= data[0] %></td>
        <td><%= data[1] %></td>
        <td><%= data[2] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Welcome</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<%= render partial: 'layouts/header' %>
  		
	    <%= yield %>
  	</div>
  </body>
</html>